/*
 * File: app/store/cheque_ver.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cheques.store.cheque_ver', {
    extend: 'Ext.data.Store',

    requires: [
        'Cheques.model.cheque_ver',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'cheque_ver',
            autoSync: true,
            model: 'Cheques.model.cheque_ver',
            proxy: {
                type: 'ajax',
                api: {
                    read: 'api/Cheque/read',
                    create: 'api/Cheque/create',
                    update: 'api/Cheque/update'
                },
                reader: {
                    type: 'json',
                    messageProperty: 'message',
                    rootProperty: 'data'
                },
                writer: {
                    type: 'json',
                    writeAllFields: true,
                    encode: true,
                    rootProperty: 'data'
                },
                listeners: {
                    exception: {
                        fn: me.onAjaxException,
                        scope: me
                    }
                }
            },
            listeners: {
                write: {
                    fn: me.onStoreWrite,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onAjaxException: function(proxy, request, operation, eOpts) {
        // Ext.MessageBox.show({
        //     title: 'Mensaje del Sistema',
        //     msg: operation.getError(),
        //     icon: Ext.MessageBox.info,
        //     buttons: Ext.Msg.OK
        // });
    },

    onStoreWrite: function(store, operation, eOpts) {
        // Ext.MessageBox.show({
        //                         title: "Mensaje del Sistema",
        //                         msg: operation.getResultSet().message,
        //                         icon: Ext.MessageBox.info,
        //                         buttons: Ext.Msg.OK
        //                     });
        // store.load({params: {id_banco:Ext._combocheque}});
    }

});