/*
 * File: app/store/impresora.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cheques.store.impresora', {
    extend: 'Ext.data.Store',

    requires: [
        'Cheques.model.impresora',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'impresora',
            autoSync: true,
            model: 'Cheques.model.impresora',
            proxy: {
                type: 'ajax',
                api: {
                    read: 'api/Impresora/read',
                    create: 'api/Impresora/create',
                    update: 'api/Impresora/update'
                },
                reader: {
                    type: 'json',
                    messageProperty: 'message',
                    rootProperty: 'data'
                },
                writer: {
                    type: 'json',
                    writeAllFields: true,
                    encode: true,
                    rootProperty: 'data'
                },
                listeners: {
                    exception: {
                        fn: me.onAjaxException,
                        scope: me
                    }
                }
            },
            listeners: {
                write: {
                    fn: me.onStoreWrite,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onAjaxException: function(proxy, request, operation, eOpts) {
        Ext.MessageBox.show({
            title: 'Mensaje del Sistema',
            msg: operation.getError(),
            icon: Ext.MessageBox.info,
            buttons: Ext.Msg.OK
        });
    },

    onStoreWrite: function(store, operation, eOpts) {
        Ext.MessageBox.show({
                                title: "Mensaje del Sistema",
                                msg: operation.getResultSet().message,
                                icon: Ext.MessageBox.info,
                                buttons: Ext.Msg.OK
                            });
        store.load();
    }

});