/*
 * File: app/view/configCheques.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cheques.view.configCheques', {
    extend: 'Ext.window.Window',
    alias: 'widget.configCheques',

    requires: [
        'Cheques.view.submenuimprimirChequesViewModel2',
        'Cheques.view.submenuimprimirChequesViewController2',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    controller: 'configcheques',
    viewModel: {
        type: 'configcheques'
    },
    modal: true,
    autoShow: true,
    draggable: false,
    height: 161,
    id: 'configCheques',
    resizable: false,
    width: 415,
    title: 'Imprimir Cheques',
    monitorResize: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            reference: 'form',
            height: 155,
            itemId: 'form',
            width: 410,
            bodyPadding: 10,
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            id: 'cmbBanco',
                                            width: 276,
                                            fieldLabel: 'Banco',
                                            name: 'cmbBanco',
                                            editable: false,
                                            displayField: 'nombre',
                                            store: 'banco',
                                            valueField: 'id',
                                            listeners: {
                                                change: 'onCmbBancoChange'
                                            }
                                        },
                                        {
                                            xtype: 'combobox',
                                            id: 'cmbCheque',
                                            fieldLabel: 'Version Cheque',
                                            name: 'cmbCheque',
                                            editable: false,
                                            displayField: 'version',
                                            store: 'cheque_ver',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'combobox',
                                            hidden: true,
                                            id: 'cmbImpresora',
                                            fieldLabel: 'Impresora',
                                            name: 'cmbImpresora',
                                            editable: false,
                                            displayField: 'nombre',
                                            store: 'impresora',
                                            valueField: 'id'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 12
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            text: 'ACEPTAR',
                                            listeners: {
                                                click: 'onButtonClick'
                                            }
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            height: 12
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            text: 'CANCELAR',
                                            listeners: {
                                                click: 'onButtonClick1'
                                            }
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            width: 12
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 12
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            hidden: true,
            id: 'panelCheque1'
        }
    ]

});