/*
 * File: app/view/imprimirCheques.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cheques.view.imprimirCheques', {
    extend: 'Ext.window.Window',
    alias: 'widget.imprimirCheques',

    requires: [
        'Cheques.view.imprimirChequesViewModel',
        'Cheques.view.imprimirChequesViewController',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    controller: 'imprimircheques',
    viewModel: {
        type: 'imprimircheques'
    },
    modal: true,
    autoShow: true,
    draggable: false,
    height: 237,
    id: 'imprimirCheques',
    resizable: false,
    width: 522,
    title: 'Imprimir Cheques',

    items: [
        {
            xtype: 'form',
            height: 189,
            width: 516,
            bodyPadding: 10,
            items: [
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'txtNombre',
                                            fieldLabel: 'Nombre',
                                            name: 'txtNombre'
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'txtCantidad',
                                            fieldLabel: 'Cantidad',
                                            name: 'txtCantidad'
                                        },
                                        {
                                            xtype: 'datefield',
                                            id: 'dtFecha',
                                            fieldLabel: 'Fecha',
                                            name: 'dtFecha',
                                            format: 'd-m-Y'
                                        },
                                        {
                                            xtype: 'combobox',
                                            id: 'cmbLeyenda',
                                            fieldLabel: 'Leyenda',
                                            name: 'cmbLeyenda',
                                            displayField: 'leyenda',
                                            store: 'leyenda',
                                            valueField: 'leyenda'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 20
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            flex: 1,
                                            text: 'Imprimir',
                                            listeners: {
                                                click: 'onButtonClick'
                                            }
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            height: 12
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            text: 'Configurar',
                                            listeners: {
                                                click: 'onButtonClick1'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 20
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            hidden: true,
            id: 'panelCheque'
        }
    ],
    listeners: {
        afterrender: 'onImprimirChequesAfterRender'
    }

});