/*
 * File: app/view/imprimirChequesViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cheques.view.imprimirChequesViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.imprimircheques',

    onButtonClick: function(button, e, eOpts) {
        Ext._txtNombre = Ext.getCmp('txtNombre').getValue();
        Ext._txtCantidad = Ext.getCmp('txtCantidad').getValue();
        Ext._dtFecha = Ext.getCmp('dtFecha').getValue();
        Ext._fechaFinal = Ext.Date.format(Ext._dtFecha, "d-m-Y");
        Ext._cmbLeyenda = Ext.getCmp('cmbLeyenda').getValue();

        // Ext.widget('wea').show();
        // Window.print();

        Ext.getCmp("panelCheque").setHtml('<iframe id="iframecheque" name="iframecheque" src="api/app/webroot/cheque/imprimircheque.php?nombre='+Ext._txtNombre+
        '&cantidad='+Ext._txtCantidad+
        '&monto='+Ext._txtCantidad+
        '&fecha='+Ext._fechaFinal+
        '&leyenda='+Ext._cmbLeyenda+
        '&lx='+Ext._lx+
        '&ly='+Ext._ly+
        '&fx='+Ext._fx+
        '&fy='+Ext._fy+
        '&nx='+Ext._nx+
        '&ny='+Ext._ny+
        '&cx='+Ext._cx+
        '&cy='+Ext._cy+
        '&mx='+Ext._mx+
        '&my='+Ext._my+'"></iframe>');


    },

    onButtonClick1: function(button, e, eOpts) {
        // Ext._txtNombre = Ext.getCmp('txtNombre').getValue();
        // Ext._txtCantidad = Ext.getCmp('txtCantidad').getValue();
        // Ext._dtFecha = Ext.getCmp('dtFecha').getValue();
        // Ext._cmbLeyenda = Ext.getCmp('cmbLeyenda').getValue();

        Ext.widget('configCheques').show();
        Ext.getCmp('imprimirCheques').destroy();
    },

    onImprimirChequesAfterRender: function(component, eOpts) {
        Ext._lx = '148'; Ext._ly = '88';//89.8
        Ext._fx = '229'; Ext._fy = '82';//83.3
        Ext._cx = '250'; Ext._cy = '95';//97.7
        Ext._nx = '125'; Ext._ny = '96';//97.7
        Ext._mx = '125'; Ext._my = '104';//105
    }

});
