/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cheques.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'Cheques.view.MyViewportViewModel',
        'Cheques.view.MyViewportViewController',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    controller: 'myviewport',
    viewModel: {
        type: 'myviewport'
    },

    items: [
        {
            xtype: 'panel',
            title: 'Cheques',
            items: [
                {
                    xtype: 'button',
                    id: 'menuConfig',
                    text: 'Imprimir Cheques',
                    menu: {
                        xtype: 'menu',
                        width: 160,
                        items: [
                            {
                                xtype: 'menuitem',
                                id: 'impCheque',
                                text: 'Imprimir Cheques',
                                listeners: {
                                    click: 'onMenuitem1Click'
                                }
                            },
                            {
                                xtype: 'menuitem',
                                text: 'Menu Item'
                            },
                            {
                                xtype: 'menuitem',
                                text: 'Menu Item'
                            }
                        ]
                    }
                }
            ]
        }
    ]

});