/*
 * File: app/view/MyViewportViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cheques.view.MyViewportViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.myviewport',

    onMenuitem1Click: function(item, e, eOpts) {
        Ext._nombrealias="imprimirCheques";
        // Ext.getStore('store'+Ext._nombrealias).load();
        // Ext.getStore('store'+Ext._nombrealias).clearFilter();
        // Ext.widget('submenu'+Ext._nombrealias).show();
        Ext.widget(Ext._nombrealias).show();
    }

});
