/*
 * File: app/view/submenuimprimirChequesViewController2.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cheques.view.submenuimprimirChequesViewController2', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.configcheques',

    onCmbBancoChange: function(field, newValue, oldValue, eOpts) {
        if (newValue!=="" && newValue!==null){
            Ext._combocheque = Ext.getCmp('cmbBanco').getValue();
            //     Ext.Ajax.request({
            //         method: 'GET',
            //         url: 'api/Cheque/configCheque',
            //         params: {id_banco: Ext._combocheque}
            //     });
        }




        // Ext._combocheque = Ext.getCmp('cmbBanco').getValue();

        // Ext.Ajax.request({
        //     method: 'GET',
        //     url: 'api/Cheque/configCheque',
        //     params: {id_banco: Ext._combocheque},
        //     success: function(response){
        //         var res = Ext.JSON.decode(response.responseText);
        //         localStorage.setItem('id_banco', Ext._combocheque);
        //         if(Ext.isEmpty(res.data)) {
        //             Ext.Msg.show({
        //                 title:'Inicio de sesión incorrecta',
        //                 message: 'Usuario y/o contraseña no válidos',
        //                 buttons: Ext.Msg.OK,
        //                 icon: Ext.Msg.ERROR,
        //                 closable: false,
        //                 draggable: false,
        //             });
        //         } else {
        //                     Ext.getCmp('login').destroy();
        //                     Ext.create('control.view.mainview', {}).show();
        //             Ext.widget('ventanaPrincipal').show();
        //             Ext.getCmp('inicioSesion').destroy();
        //         }
        //     }
        // });




        console.log(Ext._combocheque);
    },

    onButtonClick: function(button, e, eOpts) {
        Ext._cmbCheque = Ext.getCmp('cmbCheque').getValue();

        switch (Ext._cmbCheque){
            case 'Otro':
            Ext._lx = '0'; Ext._ly = '0';
            Ext._fx = '0'; Ext._fy = '0';
            Ext._cx = '0'; Ext._cy = '0';
            Ext._nx = '0'; Ext._ny = '0';
            Ext._mx = '0'; Ext._my = '0';
            break;

            default:
            Ext._lx = '148'; Ext._ly = '88';//89.8
            Ext._fx = '229'; Ext._fy = '82';//83.3
            Ext._cx = '250'; Ext._cy = '95';//97.7
            Ext._nx = '125'; Ext._ny = '96';//97.7
            Ext._mx = '125'; Ext._my = '104';//105

        }


        // Ext._loginusr = Ext.getCmp('loginusr').getValue();
        // Ext._loginpw = Ext.getCmp('loginpw').getValue();

        Ext.widget('imprimirCheques').show();
        Ext.getCmp('configCheques').destroy();
    },

    onButtonClick1: function(button, e, eOpts) {
        Ext.widget('imprimirCheques').show();
        Ext.getCmp('configCheques').destroy();
    }

});
