/*
 * File: app/view/submenuimprimirChequesViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cheques.view.submenuimprimirChequesViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.submenuimprimircheques',

    onButtonClick: function(button, e, eOpts) {
        Ext._txtNombre = Ext.getCmp('txtNombre').getValue();
        Ext._txtCantidad = Ext.getCmp('txtCantidad').getValue();
        Ext._dtFecha = Ext.getCmp('dtFecha').getValue();
        Ext._cmbLeyenda = Ext.getCmp('cmbLeyenda').getValue();

        Ext.widget('wea').show();
        Window.print();
    }

});
