/*
 * File: app/view/wea.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cheques.view.wea', {
    extend: 'Ext.window.Window',
    alias: 'widget.wea',

    requires: [
        'Cheques.view.weaViewModel',
        'Cheques.view.weaViewController',
        'Ext.form.field.Display'
    ],

    controller: 'wea',
    viewModel: {
        type: 'wea'
    },
    flex: 1,
    height: 430,
    html: '<img src="resources/img/cheque.jpg"/>',
    width: 711,
    bodyPadding: '20 10',
    title: 'My Window',

    listeners: {
        afterrender: 'onWindowAfterRender'
    },
    items: [
        {
            xtype: 'displayfield',
            shadow: false,
            floating: true,
            hidden: true,
            id: 'nombreRecibe'
        },
        {
            xtype: 'displayfield',
            shadow: false,
            floating: true,
            hidden: true,
            id: 'cantidadRecibe'
        },
        {
            xtype: 'displayfield',
            shadow: false,
            floating: true,
            hidden: true,
            id: 'montoRecibe'
        },
        {
            xtype: 'displayfield',
            shadow: false,
            floating: true,
            hidden: true,
            id: 'fechaRecibe'
        },
        {
            xtype: 'displayfield',
            shadow: false,
            floating: true,
            hidden: true,
            id: 'leyendaRecibe'
        }
    ]

});